const cta = require("./cta");
const icon = require("./icon");

module.exports = ({
  /* Setting Defaults */
  color_scheme = true,
  spread_content = false,
  /* Content Defaults */
  default_content_width = 295,
  default_heading = "",
  content_position = false,
  default_heading_offset = 0,
  default_subheading_size_mob = "md",
  default_subheading_size_dsk = "md",
  default_heading_size_mob = "2xl",
  default_heading_size_dsk = "4xl",
  default_overline_size_mob = "md",
  default_overline_size_dsk = "md",
  default_text_size_mob = "md",
  default_text_size_dsk = "",
  content_align = false,
  /* Extras */
  content_bullets = false,
  media_content_gap = false,
  /* CTA Defaults */
  multiple_ctas = false,
  default_cta_size = "full",
  default_cta_size_dsk = "large",
  default_cta_align = "vertical",
  default_cta_align_desktop = "vertical",
} = {}) => {
  return [
    {
      type: "paragraph",
      content: "Settings",
    },
    media_content_gap && {
      type: "range",
      id: "content_gap",
      label: "Content Gap",
      min: 0,
      max: 48,
      default: 0,
      step: 4,
      unit: "px",
    },
    {
      type: "number",
      id: "content_width",
      label: "Content Width (in px)",
      info: "Set to 0 for no set content width.",
      default: default_content_width,
    },
    content_position && {
      type: "select",
      id: "content_position",
      label: "Content postion on desktop",
      options: [
        { value: "", label: "Left" },
        { value: "center", label: "Center" },
        { value: "right", label: "Right" },
      ],
      default: "",
    },
    {
      type: "number",
      id: "offset_heading",
      label: "Offset Heading from Content Width (in px)",
      info: "Allows you to expand the heading to be wider than the content width. Set to 0 for no set heading offset.",
      default: default_heading_offset,
    },
    {
      type: "header",
      content: "Content spacing on mobile",
    },
    {
      type: "range",
      id: "subheading_spacing",
      label: "Subheading spacing",
      min: 0,
      max: 48,
      default: 16,
      step: 4,
      unit: "px",
    },
    {
      type: "range",
      id: "heading_spacing",
      label: "Heading spacing",
      min: 0,
      max: 48,
      default: 16,
      step: 4,
      unit: "px",
    },
    {
      type: "range",
      id: "overline_spacing",
      label: "Overline spacing",
      min: 0,
      max: 48,
      default: 16,
      step: 4,
      unit: "px",
    },
    {
      type: "range",
      id: "description_spacing",
      label: "Description spacing",
      min: 0,
      max: 48,
      default: 16,
      step: 4,
      unit: "px",
    },
    {
      type: "header",
      content: "Content spacing on desktop",
    },
    {
      type: "range",
      id: "subheading_spacing_desktop",
      label: "Subheading spacing on desktop",
      min: 0,
      max: 48,
      default: 16,
      step: 4,
      unit: "px",
    },
    {
      type: "range",
      id: "heading_spacing_desktop",
      label: "Heading spacing on desktop",
      min: 0,
      max: 48,
      default: 16,
      step: 4,
      unit: "px",
    },
    {
      type: "range",
      id: "overline_spacing_desktop",
      label: "Overline spacing on desktop",
      min: 0,
      max: 48,
      default: 16,
      step: 4,
      unit: "px",
    },
    {
      type: "range",
      id: "description_spacing_desktop",
      label: "Description spacing on desktop",
      min: 0,
      max: 48,
      default: 16,
      step: 4,
      unit: "px",
    },
    {
      type: "select",
      id: "cta_sizes",
      label: "CTA Sizes",
      options: [
        { value: "standard", label: "Standard (180px)" },
        { value: "small", label: "Small (160px)" },
        { value: "medium", label: "Medium (246px)" },
        { value: "large", label: "Large (309px)" },
        { value: "full", label: "Full (100%)" },
      ],
      default: default_cta_size,
    },
    {
      type: "select",
      id: "cta_sizes_dsk",
      label: "CTA Sizes on desktop",
      options: [
        { value: "standard", label: "Standard (180px)" },
        { value: "small", label: "Small (160px)" },
        { value: "medium", label: "Medium (246px)" },
        { value: "large", label: "Large (309px)" },
        { value: "full", label: "Full (100%)" },
      ],
      default: default_cta_size_dsk,
    },
    {
      type: "select",
      id: "cta_align",
      label: "CTA Align",
      options: [
        { value: "horizontal", label: "Horizontal" },
        { value: "vertical", label: "Vertical" },
      ],
      default: default_cta_align,
    },
    {
      type: "select",
      id: "cta_align_desktop",
      label: "CTA Align on desktop",
      options: [
        { value: "horizontal", label: "Horizontal" },
        { value: "vertical", label: "Vertical" },
      ],
      default: default_cta_align_desktop,
    },
    content_align && {
      type: "select",
      id: "content_align",
      label: "Content Align",
      options: [
        { value: "", label: "Horizontal" },
        { value: "1", label: "Vertical" },
      ],
      default: "",
    },
    {
      type: "select",
      id: "position",
      label: "Position",
      options: [
        { value: "start", label: "Left" },
        { value: "center", label: "Center" },
        { value: "end", label: "Right" },
      ],
      default: "start",
    },
    {
      type: "select",
      id: "vertical_position",
      label: "Vertical Position",
      options: [
        { value: "top", label: "Top" },
        { value: "center", label: "Center" },
        { value: "bottom", label: "Bottom" },
      ],
      default: "center",
    },
    color_scheme && {
      type: "select",
      id: "color",
      label: "Text color",
      options: [
        { value: "dark", label: "Dark" },
        { value: "light", label: "Light" },
      ],
      default: "dark",
    },
    color_scheme && {
      type: "select",
      id: "color_desk",
      label: "Text color Desktop",
      options: [
        { value: "", label: "As above" },
        { value: "dark", label: "Dark" },
        { value: "light", label: "Light" },
      ],
      default: "",
    },
    {
      type: "select",
      id: "subheading_size",
      label: "Subheading size",
      options: [
        { value: "2xs", label: "xs (10px)" },
        { value: "sm", label: "sm (12px)" },
        { value: "md", label: "md (14px)" },
        { value: "base", label: "base (16px)" },
        { value: "lg", label: "lg (18px)" },
        { value: "2xl", label: "2xl (24px)" },
      ],
      default: default_subheading_size_mob,
    },
    {
      type: "select",
      id: "heading_size",
      label: "Heading size",
      options: [
        { value: "md", label: "small (14px)" },
        { value: "base", label: "base (16px)" },
        { value: "lg", label: "lg (18px)" },
        { value: "2xl", label: "2xl (24px)" },
        { value: "3sm", label: "3sm (27px)" },
        { value: "3xl", label: "3xl (28px)" },
        { value: "4xl", label: "4xl (32px)" },
        { value: "5xl", label: "5xl (36px)" },
        { value: "6xl", label: "6xl (41px)" },
        { value: "6xxl", label: "6xxl (43px)" },
        { value: "7xl", label: "7xl (48px)" },
        { value: "8xl", label: "8xl (64px)" },
        { value: "9xl", label: "9xl (72px)" },
      ],
      default: default_heading_size_mob,
    },
    {
      type: "select",
      id: "heading_font_weight_mobile",
      label: "Heading Font Weight - Mobile",
      options: [
        { value: "", label: "As desktop" },
        { value: "font-thin", label: "Thin" },
        { value: "font-light", label: "Light" },
        { value: "font-normal", label: "Normal" },
        { value: "font-medium", label: "Medium" },
        { value: "font-bold", label: "Bold" },
      ],
      default: "",
    },

    {
      type: "select",
      id: "overline_size",
      label: "Overline size",
      options: [
        { value: "2xs", label: "xs (10px)" },
        { value: "sm", label: "sm (12px)" },
        { value: "md", label: "md (14px)" },
        { value: "base", label: "base (16px)" },
        { value: "lg", label: "lg (18px)" },
        { value: "2xl", label: "2xl (24px)" },
      ],
      default: default_overline_size_mob,
    },
    {
      type: "select",
      id: "text_size",
      label: "Text size",
      options: [
        { value: "2xs", label: "xs (10px)" },
        { value: "sm", label: "sm (12px)" },
        { value: "smd", label: "smd (13px)" },
        { value: "md", label: "md (14px)" },
        { value: "base", label: "base (16px)" },
        { value: "lg", label: "lg (18px)" },
        { value: "2xl", label: "2xl (24px)" },
      ],
      default: default_text_size_mob,
    },
    {
      type: "paragraph",
      content: "Desktop settings",
    },
    ...(spread_content ?
      [
        {
          type: "checkbox",
          id: "spread_content",
          label: "Spread Content?",
          info: "Matches content height to its container's height",
          default: false,
        },
      ]
    : []),
    {
      type: "select",
      id: "position_desktop",
      label: "Position on desktop",
      options: [
        { value: "", label: "as above" },
        { value: "start", label: "Left" },
        { value: "center", label: "Center" },
        { value: "end", label: "Right" },
      ],
      default: "",
    },
    {
      type: "select",
      id: "vertical_position_desktop",
      label: "Vertical position on desktop",
      options: [
        { value: "top", label: "Top" },
        { value: "center", label: "Center" },
        { value: "bottom", label: "Bottom" },
      ],
      default: "center",
    },
    {
      type: "select",
      id: "subheading_size_desktop",
      label: "Subheading size on desktop",
      options: [
        { value: "", label: "as above" },
        { value: "2xs", label: "xs (10px)" },
        { value: "sm", label: "sm (12px)" },
        { value: "md", label: "md (14px)" },
        { value: "base", label: "base (16px)" },
        { value: "lg", label: "lg (18px)" },
        { value: "2xl", label: "2xl (24px)" },
      ],
      default: default_subheading_size_dsk,
    },
    {
      type: "select",
      id: "heading_size_desktop",
      label: "Heading size on desktop",
      options: [
        { value: "", label: "as above" },
        { value: "md", label: "md (14px)" },
        { value: "base", label: "base (16px)" },
        { value: "lg", label: "lg (18px)" },
        { value: "2xl", label: "2xl (24px)" },
        { value: "3sm", label: "3sm (27px)" },
        { value: "3xl", label: "3xl (28px)" },
        { value: "4xl", label: "4xl (32px)" },
        { value: "5xl", label: "5xl (36px)" },
        { value: "6xl", label: "6xl (41px)" },
        { value: "6xxl", label: "6xxl (43px)" },
        { value: "7xl", label: "7xl (48px)" },
        { value: "8xl", label: "8xl (64px)" },
        { value: "9xl", label: "9xl (72px)" },
      ],
      default: default_heading_size_dsk,
    },
    {
      type: "select",
      id: "overline_size_desktop",
      label: "Overline size on desktop",
      options: [
        { value: "", label: "as above" },
        { value: "2xs", label: "xs (10px)" },
        { value: "sm", label: "sm (12px)" },
        { value: "md", label: "md (14px)" },
        { value: "base", label: "base (16px)" },
        { value: "lg", label: "lg (18px)" },
        { value: "2xl", label: "2xl (24px)" },
      ],
      default: default_overline_size_dsk,
    },
    {
      type: "select",
      id: "text_size_desktop",
      label: "Text size on desktop",
      options: [
        { value: "", label: "as above" },
        { value: "2xs", label: "xs (10px)" },
        { value: "sm", label: "sm (12px)" },
        { value: "smd", label: "smd (13px)" },
        { value: "md", label: "md (14px)" },
        { value: "base", label: "base (16px)" },
        { value: "lg", label: "lg (18px)" },
        { value: "2xl", label: "2xl (24px)" },
      ],
      default: default_text_size_dsk,
    },
    {
      type: "select",
      id: "heading_font_weight",
      label: "Heading Font Weight - Desk",
      options: [
        { value: "", label: "Normal" },
        { value: "font-thin", label: "Thin" },
        { value: "font-light", label: "Light" },
        { value: "font-medium", label: "Medium" },
        { value: "font-bold", label: "Bold" },
      ],
      default: "",
    },
    {
      type: "header",
      content: "Content",
    },
    {
      type: "paragraph",
      content:
        "Wrap text with [highlight]...[/highlight] to display it in highlight color",
    },
    {
      type: "richtext",
      id: "subheading",
      label: "Subheading",
    },
    (default_heading !== "" && {
      type: "richtext",
      id: "heading",
      label: "Heading",
      default: `<p>${default_heading}</p>`,
    }) || {
      type: "richtext",
      id: "heading",
      label: "Heading",
    },
    {
      type: "inline_richtext",
      id: "overline",
      label: "Overline",
    },
    {
      type: "richtext",
      id: "text",
      label: "Description",
    },
    ...(content_bullets ?
      icon({
        id: "bullet_icon",
        label: "Bullet Icon",
        default_icon: "none",
      })
    : []),
    content_bullets && {
      type: "richtext",
      id: "bullet_content",
      label: "Bullet content",
      info: "Insert bullets separated by ;",
    },
    {
      type: "select",
      id: "text_tranform",
      label: "Text transform",
      options: [
        { value: "", label: "Normal" },
        { value: "uppercase", label: "Uppercase" },
        { value: "capitalize", label: "Capitalize" },
      ],
      default: "",
    },
    {
      type: "select",
      id: "text_weight",
      label: "Font Weight",
      options: [
        { value: "", label: "Normal" },
        { value: "font-light", label: "Light" },
        { value: "font-medium", label: "Medium" },
        { value: "font-semibold", label: "Semibold" },
        { value: "font-bold", label: "Bold" },
      ],
      default: "",
    },
    {
      type: "select",
      id: "heading_tracking_font",
      label: "Heading Font Tracking",
      options: [
        { value: "tracking-0", label: "None" },
        { value: "tracking-standard", label: "1.92px Spacing" },
        { value: "tracking-wide", label: "2.4px Spacing" },
      ],
      default: "tracking-0",
    },
    {
      type: "checkbox",
      id: "text_undeline",
      label: "Text underline?",
      info: "Add underlinefor description",
      default: false,
    },
    ...cta({
      default_text: "",
      default_icon: "none",
    }),
    {
      type: "checkbox",
      id: "cta_margin_end",
      label: "Force CTA bottom",
      default: false,
    },
    ...(multiple_ctas ?
      cta({
        index: 2,
        default_text: "",
        default_style: "secondary",
        default_icon: "none",
      })
    : []),
  ].filter(Boolean);
};
